POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "video node",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/bb332f72-ac18-49c1-a586-3c6c570a1768
Content-Type: application/json

{
    "title": "video 2",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/bb332f72-ac18-49c1-a586-3c6c570a1768